title: "Soonha Hwang"
description: "German Syntax · Corpus Linguistics · Linguistic Variation"

theme: minima

header_pages:
  - publications.md
  - projects.md
  - teaching.md
  - awards.md
  - contact.md
