title: "Soonha Hwang"
description: "German Linguistics · Corpus Linguistics · Syntax"

theme: minima

header_pages:
  - publications.md
  - projects.md
  - teaching.md
  - awards.md
  - contact.md

author:
  name: "Soonha Hwang"

minima:
  skin: classic

show_excerpts: false
